//
// Generated file, do not edit! Created by opp_msgtool 6.1 from NoRerouteMessage.msg.
//

#ifndef __VEINS_NOREROUTEMESSAGE_M_H
#define __VEINS_NOREROUTEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class NoRerouteMessage;

}  // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>NoRerouteMessage.msg:7</tt> by opp_msgtool.
 * <pre>
 * packet NoRerouteMessage extends BaseFrame1609_4
 * {
 *     string roadId;
 *     LAddress::L2Type senderAddress = -1;
 * }
 * </pre>
 */
class NoRerouteMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string roadId;
    LAddress::L2Type senderAddress = -1;

  private:
    void copy(const NoRerouteMessage& other);

  protected:
    bool operator==(const NoRerouteMessage&) = delete;

  public:
    NoRerouteMessage(const char *name=nullptr, short kind=0);
    NoRerouteMessage(const NoRerouteMessage& other);
    virtual ~NoRerouteMessage();
    NoRerouteMessage& operator=(const NoRerouteMessage& other);
    virtual NoRerouteMessage *dup() const override {return new NoRerouteMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRoadId() const;
    virtual void setRoadId(const char * roadId);

    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<NoRerouteMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NoRerouteMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NoRerouteMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::NoRerouteMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::NoRerouteMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_NOREROUTEMESSAGE_M_H

