//
// Generated file, do not edit! Created by opp_msgtool 6.1 from FCRMessage.msg.
//

#ifndef __VEINS_FCRMESSAGE_M_H
#define __VEINS_FCRMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class FCRMessage;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace veins {

/**
 * Class generated from <tt>FCRMessage.msg:6</tt> by opp_msgtool.
 * <pre>
 * packet FCRMessage extends BaseFrame1609_4
 * {
 *     int msgType;          // 0 = CONGESTION_REPORT, 1 = REROUTE_GUIDANCE
 *     string roadId;        // always a VALID SUMO edge id
 *     double rerouteProb;   // α
 * }
 * </pre>
 */
class FCRMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int msgType = 0;
    ::omnetpp::opp_string roadId;
    double rerouteProb = 0;

  private:
    void copy(const FCRMessage& other);

  protected:
    bool operator==(const FCRMessage&) = delete;

  public:
    FCRMessage(const char *name=nullptr, short kind=0);
    FCRMessage(const FCRMessage& other);
    virtual ~FCRMessage();
    FCRMessage& operator=(const FCRMessage& other);
    virtual FCRMessage *dup() const override {return new FCRMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMsgType() const;
    virtual void setMsgType(int msgType);

    virtual const char * getRoadId() const;
    virtual void setRoadId(const char * roadId);

    virtual double getRerouteProb() const;
    virtual void setRerouteProb(double rerouteProb);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FCRMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FCRMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::FCRMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::FCRMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_FCRMESSAGE_M_H

