//
// Generated file, do not edit! Created by opp_msgtool 6.1 from ICDDRMessage.msg.
//

#ifndef __VEINS_ICDDRMESSAGE_M_H
#define __VEINS_ICDDRMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class ICDDRSpeedReport;
class ICDDRCAM;

}  // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>ICDDRMessage.msg:8</tt> by opp_msgtool.
 * <pre>
 * // Vehicle -> RSU: report low-speed condition (alpha breach)
 * packet ICDDRSpeedReport extends BaseFrame1609_4
 * {
 *     string roadId;                     // SUMO edge id
 *     LAddress::L2Type senderAddress = -1;
 *     double v20;                        // avg speed estimate (m/s)
 *     double vFree;                      // free flow estimate (m/s)
 *     double alpha;                      // v20 / vFree
 *     double senderX;
 *     double senderY;
 * }
 * </pre>
 */
class ICDDRSpeedReport : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string roadId;
    LAddress::L2Type senderAddress = -1;
    double v20 = 0;
    double vFree = 0;
    double alpha = 0;
    double senderX = 0;
    double senderY = 0;

  private:
    void copy(const ICDDRSpeedReport& other);

  protected:
    bool operator==(const ICDDRSpeedReport&) = delete;

  public:
    ICDDRSpeedReport(const char *name=nullptr, short kind=0);
    ICDDRSpeedReport(const ICDDRSpeedReport& other);
    virtual ~ICDDRSpeedReport();
    ICDDRSpeedReport& operator=(const ICDDRSpeedReport& other);
    virtual ICDDRSpeedReport *dup() const override {return new ICDDRSpeedReport(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRoadId() const;
    virtual void setRoadId(const char * roadId);

    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<ICDDRSpeedReport*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);

    virtual double getV20() const;
    virtual void setV20(double v20);

    virtual double getVFree() const;
    virtual void setVFree(double vFree);

    virtual double getAlpha() const;
    virtual void setAlpha(double alpha);

    virtual double getSenderX() const;
    virtual void setSenderX(double senderX);

    virtual double getSenderY() const;
    virtual void setSenderY(double senderY);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ICDDRSpeedReport& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ICDDRSpeedReport& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ICDDRMessage.msg:19</tt> by opp_msgtool.
 * <pre>
 * // RSU/Vehicle -> Vehicle: Congestion Alert Message (CAM)
 * packet ICDDRCAM extends BaseFrame1609_4
 * {
 *     string camId;                      // unique id: rsuId-edge-seq
 *     string roadId;                     // congested edge id
 *     int ttl;                           // adaptive TTL (max forwards)
 *     int hopsLeft;                      // decremented at each forward
 *     double cd;                         // congestion score
 *     int seqNo;                         // optional
 * 
 *     // Sender Travel Path Line (TPL) parameters for relevance calc
 *     double senderSlope;
 *     double senderIntercept;
 *     double senderX;
 *     double senderY;
 * }
 * </pre>
 */
class ICDDRCAM : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string camId;
    ::omnetpp::opp_string roadId;
    int ttl = 0;
    int hopsLeft = 0;
    double cd = 0;
    int seqNo = 0;
    double senderSlope = 0;
    double senderIntercept = 0;
    double senderX = 0;
    double senderY = 0;

  private:
    void copy(const ICDDRCAM& other);

  protected:
    bool operator==(const ICDDRCAM&) = delete;

  public:
    ICDDRCAM(const char *name=nullptr, short kind=0);
    ICDDRCAM(const ICDDRCAM& other);
    virtual ~ICDDRCAM();
    ICDDRCAM& operator=(const ICDDRCAM& other);
    virtual ICDDRCAM *dup() const override {return new ICDDRCAM(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getCamId() const;
    virtual void setCamId(const char * camId);

    virtual const char * getRoadId() const;
    virtual void setRoadId(const char * roadId);

    virtual int getTtl() const;
    virtual void setTtl(int ttl);

    virtual int getHopsLeft() const;
    virtual void setHopsLeft(int hopsLeft);

    virtual double getCd() const;
    virtual void setCd(double cd);

    virtual int getSeqNo() const;
    virtual void setSeqNo(int seqNo);

    virtual double getSenderSlope() const;
    virtual void setSenderSlope(double senderSlope);

    virtual double getSenderIntercept() const;
    virtual void setSenderIntercept(double senderIntercept);

    virtual double getSenderX() const;
    virtual void setSenderX(double senderX);

    virtual double getSenderY() const;
    virtual void setSenderY(double senderY);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ICDDRCAM& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ICDDRCAM& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::ICDDRSpeedReport *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::ICDDRSpeedReport*>(ptr.get<cObject>()); }
template<> inline veins::ICDDRCAM *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::ICDDRCAM*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_ICDDRMESSAGE_M_H

