//
// Generated file, do not edit! Created by opp_msgtool 6.1 from RiderMessage.msg.
//

#ifndef __VEINS_RIDERMESSAGE_M_H
#define __VEINS_RIDERMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class RiderMessage;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace veins {

/**
 * Class generated from <tt>RiderMessage.msg:5</tt> by opp_msgtool.
 * <pre>
 * packet RiderMessage extends BaseFrame1609_4
 * {
 *     string roadId;
 *     int congestionFactor;
 *     int ttl;
 *     bool isRequest;
 *     bool isResponse;
 * }
 * </pre>
 */
class RiderMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string roadId;
    int congestionFactor = 0;
    int ttl = 0;
    bool isRequest_ = false;
    bool isResponse_ = false;

  private:
    void copy(const RiderMessage& other);

  protected:
    bool operator==(const RiderMessage&) = delete;

  public:
    RiderMessage(const char *name=nullptr, short kind=0);
    RiderMessage(const RiderMessage& other);
    virtual ~RiderMessage();
    RiderMessage& operator=(const RiderMessage& other);
    virtual RiderMessage *dup() const override {return new RiderMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRoadId() const;
    virtual void setRoadId(const char * roadId);

    virtual int getCongestionFactor() const;
    virtual void setCongestionFactor(int congestionFactor);

    virtual int getTtl() const;
    virtual void setTtl(int ttl);

    virtual bool isRequest() const;
    virtual void setIsRequest(bool isRequest);

    virtual bool isResponse() const;
    virtual void setIsResponse(bool isResponse);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RiderMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RiderMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::RiderMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::RiderMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_RIDERMESSAGE_M_H

