//
// Generated file, do not edit! Created by opp_msgtool 6.1 from PandoraMessage.msg.
//

#ifndef __VEINS_PANDORAMESSAGE_M_H
#define __VEINS_PANDORAMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class PandoraMessage;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>PandoraMessage.msg:7</tt> by opp_msgtool.
 * <pre>
 * packet PandoraMessage extends BaseFrame1609_4
 * {
 *     string roadId;
 *     double roadWeight;             // w_ij
 * 
 *     // Phase-4: subarea support
 *     int subareaId;                 // [0..k-1]
 *     double avgSpeed;               // avg speed observed for this road in this subarea
 *     int samples;                   // number of samples used in avgSpeed
 * 
 *     Coord criticalCenter;
 *     double anchorRadius;
 *     simtime_t timestamp;
 * 
 *     LAddress::L2Type senderAddress = -1;
 * }
 * </pre>
 */
class PandoraMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string roadId;
    double roadWeight = 0;
    int subareaId = 0;
    double avgSpeed = 0;
    int samples = 0;
    Coord criticalCenter;
    double anchorRadius = 0;
    ::omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    LAddress::L2Type senderAddress = -1;

  private:
    void copy(const PandoraMessage& other);

  protected:
    bool operator==(const PandoraMessage&) = delete;

  public:
    PandoraMessage(const char *name=nullptr, short kind=0);
    PandoraMessage(const PandoraMessage& other);
    virtual ~PandoraMessage();
    PandoraMessage& operator=(const PandoraMessage& other);
    virtual PandoraMessage *dup() const override {return new PandoraMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRoadId() const;
    virtual void setRoadId(const char * roadId);

    virtual double getRoadWeight() const;
    virtual void setRoadWeight(double roadWeight);

    virtual int getSubareaId() const;
    virtual void setSubareaId(int subareaId);

    virtual double getAvgSpeed() const;
    virtual void setAvgSpeed(double avgSpeed);

    virtual int getSamples() const;
    virtual void setSamples(int samples);

    virtual const Coord& getCriticalCenter() const;
    virtual Coord& getCriticalCenterForUpdate() { return const_cast<Coord&>(const_cast<PandoraMessage*>(this)->getCriticalCenter());}
    virtual void setCriticalCenter(const Coord& criticalCenter);

    virtual double getAnchorRadius() const;
    virtual void setAnchorRadius(double anchorRadius);

    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);

    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<PandoraMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PandoraMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PandoraMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::PandoraMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::PandoraMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_PANDORAMESSAGE_M_H

